var b,e,f;function g(a){return"string"==typeof a?document.getElementById(a):a}function h(){var a=g("asm");if(a&&(a=a.value)){g("out").value="";var c=k();c.open("POST","compile.php");c.setRequestHeader("Content-type","application/x-www-form-urlencoded");c.onreadystatechange=function(){4==c.readyState&&eval(c.responseText)};c.send("asm="+encodeURIComponent(a))}}function m(a){return 32>a||127<=a?".":String.fromCharCode(a)}function p(a){return a.toString(2).padStart(8,"0")}
function q(a){return a.toString(10).padStart(3," ")}function t(a){return a.toString(16).padStart(2,"0")}function u(a){return a.toString(16).padStart(4,"0")}function w(){b.u=1;b.l=65532;b.l=x();b.m=256;b.g=0;b.i=0;b.j=0;b.h=32}function y(a){b.u=0;SO(["HALT:"+a])}function A(a){0<=b.m?(b.m--,B((b.m&255)+256,a)):y("stack full: "+b.m)}function C(){if(256>b.m){var a=D((b.m&255)+256);b.m++;return a}y("stack empty");return b.u=0}function E(){b.v++;return 255&D(b.l++)}function x(){return E()+(E()<<8)}
function F(a,c){b.memory[a]=c&255}function G(a){return a in b.memory?b.memory[a]:y("GLOBAL(cpu6502).memory location $"+u(a)+" unavailable")}function B(a,c){a&=65535;c&=255;for(var d in f){var l=f[d];if(l.A&&"x"!==l.A(a,c))return}F(a,c)}function D(a){a&=65535;for(var c in f){var d=f[c];if(d.S&&(d=d.S(a),"x"!==d))return d}return G(a)}function J(a){127<a?b.l=b.l-(256-a):b.l+=a}function K(a,c){var d=255<a+c;"undefined"!=typeof d&&(b.h=d?b.h|1:b.h&-2);c=a-c;L(0==c);M(c&128)}
function N(a){if(b.h&8){var c=15+(b.g&15)-(a&15)+(b.h&1);if(16>c){var d=0;c-=6}else d=16,c-=16;d+=240+(b.g&240)-(a&240);256>d?(b.h&=254,b.h&191&&128>d&&(b.h&=191),d-=96):(b.h|=1,b.h&191&&384<=d&&(b.h&=191));d+=c}else d=255+b.g-a+(b.h&1),256>d?(b.h&=254,b.h&191&&128>d&&(b.h&=191)):(b.h|=1,b.h&191&&384<=d&&(b.h&=191));b.g=d&255;L(0==b.g);M(b.g&128)}
function O(a){b.h=(b.g^a)&128?b.h&191:b.h|64;if(b.h&8){var c=(b.g&15)+(a&15)+(b.h&1);10<=c&&(c=16|c+6&15);c+=(b.g&240)+(a&240);160<=c?(b.h|=1,b.h&191&&384<=c&&(b.h&=191),c+=96):(b.h&=254,b.h&191&&128>c&&(b.h&=191))}else c=b.g+a+(b.h&1),256<=c?(b.h|=1,b.h&191&&384<=c&&(b.h&=191)):(b.h&=254,b.h&191&&128>c&&(b.h&=191));b.g=c&255;L(0==b.g);M(b.g&128)}
function P(a,c){function d(v){v=v||window.event;v.preventDefault();r[0]=v.clientX;r[1]=v.clientY;document.onmouseup=n;document.onmousemove=l}function l(v){v=v||window.event;v.preventDefault();var H=[];H[0]=r[0]-v.clientX;H[1]=r[1]-v.clientY;r[0]=v.clientX;r[1]=v.clientY;a.style.top=a.offsetTop-H[1]+"px";a.style.left=a.offsetLeft-H[0]+"px"}function n(){document.onmouseup=null;document.onmousemove=null}var r=[0,0];c.length||(a.onmousedown=d);for(var z=0;z<c.length;z++)c[z].onmousedown=d}
function Q(){var a=document.querySelectorAll("div.draggable"),c;for(c of a){a=[];const n=c.childNodes;for(var d=0;d<n.length;d++){var l=n[d];l.className&&l.className.match(/handle/)&&a.push(l)}P(c,a)}}function S(a){a.preventDefault()}
function T(a){a.preventDefault();if(a.dataTransfer.items)for(var c=0;c<a.dataTransfer.items.length;c++)"file"===a.dataTransfer.items[c].kind&&U(a.dataTransfer.items[c].getAsFile());else for(c=0;c<a.dataTransfer.files.length;c++)U(a.dataTransfer.files[c]);a.dataTransfer.items?a.dataTransfer.items.clear():a.dataTransfer.clearData()}
function V(){e={};R(0);var a=0;setInterval(function(){a+=e.U;var c=Math.floor(a/100);if(!(1>c)){a-=100*c;for(var d=0;d<c;d++)if(b.u){var l=E();if(l in W)W[l]();else b.u=0,SO(["HALT - unknown opcode $"+t(l)+" @ $"+u(b.l)])}}},10)}function L(a){"undefined"!=typeof a&&(b.h=a?b.h|2:b.h&-3)}function M(a){"undefined"!=typeof a&&(b.h=a?b.h|128:b.h&-129)}
function X(){g("assembla").addEventListener("click",h);g("ex").addEventListener("change",Y);Q();setInterval(function(){var a=255&b.g,c=255&b.i,d=255&b.j;g("cy").value=b.v;g("PC").value="$"+u(b.l);g("A").value="$"+t(a)+" "+m(a)+" "+q(a)+" %"+p(a);g("X").value="$"+t(c)+" "+m(c)+" "+q(c)+" %"+p(c);g("Y").value="$"+t(d)+" "+m(d)+" "+q(d)+" %"+p(d);f.T.show()},33)}I=function(a){var c=[];a=atob(a);for(var d=0;d<a.length;d++)c[d]=a.charCodeAt(d);R(0);f.T.clear();b.u=0;b.memory=c;w()};
function aa(){function a(){var l=g("ln");if(d!=c.scrollHeight){d=c.scrollHeight;for(var n=c.scrollHeight/20,r=[],z=1;z<n;z++)r.push(z);l.innerHTML=r.join("\n")}l.scrollTop=c.scrollTop}var c=g("asm"),d=-1;c.onscroll=a;a()}function Y(){var a=g("ex");if(!(0>a.value)){var c=k();c.open("GET","load_ex.php?v="+a.value);c.onreadystatechange=function(){4==c.readyState&&eval("SS"+c.responseText)};c.send()}}
function k(){try{return new XMLHttpRequest}catch(a){}try{return new ActiveXObject("Msxml2.XMLHTTP")}catch(a){}try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(a){}throw Error("XMLHttpRequest non disponibile");}
onload=function(){f={};document.addEventListener("drop",T);document.addEventListener("dragover",S);aa();ba();b={memory:[]};for(var a=0;65535>=a;a++)b.memory[a]=0;b.v=0;b.u=0;b.l=0;b.m=0;b.g=0;b.i=0;b.j=0;b.h=0;w();if(!f)throw g("body").innerHTML="<div style=background:red;color:white;padding:5px;font-weight:bold>errore fatale:<br>!GLOBAL(plugins)</div>","fatal";ca();da();ea();fa();ha();V();X()};
var W=[function(){b.u=0},function(){var a=E()+b.i;a=D(a)+(D(a+1)<<8);b.g|=a;L(0==b.g);M(b.g&128)},,,,function(){var a=E();b.g|=D(a);L(0==b.g);M(b.g&128)},function(){var a=E(),c=D(a);b.h=b.h&254|c>>7&1;c<<=1;B(a,c);L(0==c);M(c&128)},,function(){A(b.h)},function(){b.g|=E();L(0==b.g);M(b.g&128)},function(){b.h=b.h&254|b.g>>7&1;b.g=b.g<<1;L(0==b.g);M(b.g&128)},,,function(){b.g|=D(x());L(0==b.g);M(b.g&128)},function(){var a=x(),c=D(a);b.h=b.h&254|c>>7&1;c<<=1;B(a,c);L(0==c);M(c&128)},,function(){var a=
E();0==(b.h&128)&&J(a)},function(){var a=E();a=D(a)+(D(a+1)<<8)+b.j;b.g|=D(a);L(0==b.g);M(b.g&128)},,,,function(){var a=E()+b.i&255;b.g|=D(a);L(0==b.g);M(b.g&128)},function(){var a=E()+b.i&255,c=D(a);b.h=b.h&254|c>>7&1;c<<=1;B(a,c);L(0==c);M(c&128)},,function(){b.h&=254},function(){var a=x()+b.j;b.g|=D(a);L(0==b.g);M(b.g&128)},,,,function(){var a=x()+b.i;b.g|=D(a);L(0==b.g);M(b.g&128)},function(){var a=x()+b.i,c=D(a);b.h=b.h&254|c>>7&1;c<<=1;B(a,c);L(0==c);M(c&128)},,function(){var a=x(),c=b.l-1;
A(c>>8&255);A(c&255);b.l=a},function(){var a=E()+b.i&255;a=D(a)+(D(a+1)<<8);b.g&=a;L(0==b.g);M(b.g&128)},,,function(){var a=E();a=D(a);L(a&0==b.g);b.h=b.h&63|a&192},function(){var a=E();b.g&=D(a);L(0==b.g);M(b.g&128)},function(){var a=b.h&1,c=E(),d=D(c);b.h=b.h&254|d>>7&1;d=d<<1|a;B(c,d);L(0==d);M(d&128)},,function(){b.h=C()|32},function(){b.g&=E();L(0==b.g);M(b.g&128)},function(){var a=b.h&1;b.h=b.h&254|b.g>>7&1;b.g=b.g<<1;b.g|=a;L(0==b.g);M(b.g&128)},,function(){var a=D(x());L(a&0==b.g);L(a&0==
b.g);b.h=b.h&63|a&192},function(){var a=D(x());b.g&=a;L(0==b.g);M(b.g&128)},function(){var a=b.h&1,c=x(),d=D(c);b.h=b.h&254|d>>7&1;d=d<<1|a;B(c,d);L(0==d);M(d&128)},,function(){var a=E();b.h&128&&J(a)},function(){var a=E();a=D(a)+(D(a+1)<<8)+b.j;b.g&=D(a);L(0==b.g);M(b.g&128)},,,,function(){var a=E();a=D(a)+(D(a+1)<<8)+b.i;b.g&=D(a);L(0==b.g);M(b.g&128)},function(){var a=b.h&1,c=E()+b.i&255,d=D(c);b.h=b.h&254|d>>7&1;d=d<<1|a;B(c,d);L(0==d);M(d&128)},,function(){b.h|=1},function(){var a=x()+b.j;a=
D(a);b.g&=a;L(0==b.g);M(b.g&128)},,,,function(){var a=x()+b.i;a=D(a);b.g&=a;L(0==b.g);M(b.g&128)},function(){var a=b.h&1,c=x()+b.i,d=D(c);b.h=b.h&254|d>>7&1;d=d<<1|a;B(c,d);L(0==d);M(d&128)},,function(){},function(){var a=E()+b.i&255;a=D(a)+(D(a+1)<<8);b.g^=D(a);L(0==b.g);M(b.g&128)},,,,function(){var a=E()+b.i&255;a=D(a);b.g^=a;L(0==b.g);M(b.g&128)},function(){var a=E()&255,c=D(a);b.h=b.h&254|c&1;c>>=1;B(a,c);L(0==c);M(c&128)},,function(){A(b.g)},function(){b.g^=E();L(0==b.g);M(b.g&128)},function(){b.h=
b.h&254|b.g&1;b.g=b.g>>1;L(0==b.g);M(b.g&128)},,function(){b.l=x()},function(){var a=x();a=D(a);b.g^=a;L(0==b.g);M(b.g&128)},function(){var a=x(),c=D(a);b.h=b.h&254|c&1;c>>=1;B(a,c);L(0==c);M(c&128)},,function(){var a=E();0==(b.h&64)&&J(a)},function(){var a=E();a=D(a)+(D(a+1)<<8)+b.j;b.g^=D(a);L(0==b.g);M(b.g&128)},,,,function(){var a=E()+b.i&255;b.g^=D(a);L(0==b.g);M(b.g&128)},function(){var a=E()+b.i&255,c=D(a);b.h=b.h&254|c&1;c>>=1;B(a,c);L(0==c);M(c&128)},,function(){},function(){var a=x()+b.j;
a=D(a);b.g^=a;L(0==b.g);M(b.g&128)},,,,function(){var a=x()+b.i;a=D(a);b.g^=a;L(0==b.g);M(b.g&128)},function(){var a=x()+b.i,c=D(a);b.h=b.h&254|c&1;c>>=1;B(a,c);L(0==c);M(c&128)},,function(){b.l=C()+1|C()<<8},function(){var a=E()+b.i&255;a=D(a)+(D(a+1)<<8);a=D(a);O(a)},,,,function(){var a=E();a=D(a);O(a)},function(){var a=b.h&1,c=E(),d=D(c);b.h=b.h&254|d&1;d>>=1;a&&(d|=128);B(c,d);L(0==d);M(d&128)},,function(){b.g=C();L(0==b.g);M(b.g&128)},function(){var a=E();O(a)},function(){var a=b.h&1;b.h=b.h&
254|b.g&1;b.g=b.g>>1;a&&(b.g|=128);L(0==b.g);M(b.g&128)},,function(){},function(){var a=x();a=D(a);O(a)},function(){var a=b.h&1,c=x(),d=D(c);b.h=b.h&254|d&1;d>>=1;a&&(d|=128);B(c,d);L(0==d);M(d&128)},,function(){var a=E();b.h&64&&J(a)},function(){var a=E();a=D(a)+(D(a+1)<<8);a=D(a+b.j);O(a)},,,,function(){var a=E()+b.i&255;a=D(a);b.h=b.h&254|a&1;O(a)},function(){var a=b.h&1,c=E()+b.i&255,d=D(c);b.h=b.h&254|d&1;d>>=1;a&&(d|=128);B(c,d);L(0==d);M(d&128)},,function(){},function(){var a=x();a=D(a+b.j);
O(a)},,,,function(){var a=x();a=D(a+b.i);O(a)},function(){var a=x()+b.i,c=D(a);b.h=b.h&254|c&1;(c>>=1)&&(c|=128);B(a,c);L(0==c);M(c&128)},,,function(){var a=E()+b.i&255;a=D(a)+(D(a+1)<<8);B(a,b.g)},,,function(){B(E(),b.j)},function(){B(E(),b.g)},function(){B(E(),b.i)},,function(){b.j=b.j-1&255;L(0==b.j);M(b.j&128)},,function(){b.g=b.i&255;L(0==b.g);M(b.g&128)},,function(){B(x(),b.j)},function(){B(x(),b.g)},function(){B(x(),b.i)},,function(){var a=E();0==(b.h&1)&&J(a)},function(){var a=E();a=D(a)+
(D(a+1)<<8)+b.j;B(a,b.g)},,,function(){B(E()+b.i,b.j)},function(){B(E()+b.i,b.g)},function(){B(E()+b.j,b.i)},,function(){b.g=b.j&255;L(0==b.g);M(b.g&128)},function(){B(x()+b.j,b.g)},function(){b.m=b.i&255},,,function(){B(x()+b.i,b.g)},,,function(){b.j=E();L(0==b.j);M(b.j&128)},function(){var a=E()+b.i&255;a=D(a)+(D(a+1)<<8);b.g=D(a);L(0==b.g);M(b.g&128)},function(){b.i=E();L(0==b.i);M(b.i&128)},,function(){b.j=D(E());L(0==b.j);M(b.j&128)},function(){b.g=D(E());L(0==b.g);M(b.g&128)},function(){b.i=
D(E());L(0==b.i);M(b.i&128)},,function(){b.j=b.g&255;L(0==b.j);M(b.j&128)},function(){b.g=E();L(0==b.g);M(b.g&128)},function(){b.i=b.g&255;L(0==b.i);M(b.i&128)},,function(){b.j=D(x());L(0==b.j);M(b.j&128)},function(){b.g=D(x());L(0==b.g);M(b.g&128)},function(){b.i=D(x());L(0==b.i);M(b.i&128)},,function(){var a=E();b.h&1&&J(a)},function(){var a=E();a=D(a)+(D(a+1)<<8)+b.j;b.g=D(a);L(0==b.g);M(b.g&128)},,,function(){b.j=D(E()+b.i);L(0==b.j);M(b.j&128)},function(){b.g=D(E()+b.i&255);L(0==b.g);M(b.g&128)},
function(){b.i=D(E()+b.j);L(0==b.i);M(b.i&128)},,function(){b.h&=191},function(){var a=x()+b.j;b.g=D(a);L(0==b.g);M(b.g&128)},function(){b.i=b.m&255},,function(){var a=x()+b.i;b.j=D(a);L(0==b.j);M(b.j&128)},function(){var a=x()+b.i;b.g=D(a);L(0==b.g);M(b.g&128)},function(){var a=x()+b.j;b.i=D(a);L(0==b.i);M(b.i&128)},,function(){var a=E();b.h=255<b.j+a?b.h|1:b.h&254;a=b.j-a;L(0==a);M(a&128)},function(){var a=E();a=D(a)+(D(a+1)<<8)+b.j;a=D(a);K(b.g,a)},,,function(){var a=D(E());K(b.j,a)},function(){var a=
D(E());K(b.g,a)},function(){var a=E(),c=D(a);--c;B(a,c&255);L(0==c);M(c&128)},,function(){b.j=b.j+1&255;L(0==b.j);M(b.j&128)},function(){var a=E();K(b.g,a)},function(){b.i=b.i-1&255;L(0==b.i);M(b.i&128)},,function(){var a=D(x());K(b.j,a)},function(){var a=D(x());K(b.g,a)},function(){var a=x(),c=D(a);--c;c&=255;B(a,c);L(0==c);M(c&128)},,function(){var a=E();0==(b.h&2)&&J(a)},function(){var a=E();a=D(a)+(D(a+1)<<8)+b.j;a=D(a);K(b.g,a)},,,,function(){var a=D(E()+b.i);K(b.g,a)},function(){var a=E()+b.i,
c=D(a);--c;c&=255;B(a,c);L(0==c);M(c&128)},,function(){b.h&=247},function(){var a=x()+b.j;a=D(a);K(b.g,a)},,,,function(){var a=x()+b.i;a=D(a);K(b.g,a)},function(){var a=x()+b.i,c=D(a);--c;c&=255;B(a,c);L(0==c);M(c&128)},,function(){var a=E();K(b.i,a)},function(){var a=E()+b.i&255;a=D(a)+(D(a+1)<<8);a=D(a);N(a)},,,function(){var a=D(E());K(b.i,a)},function(){var a=E();a=D(a);N(a)},function(){var a=E(),c=D(a);++c;c&=255;B(a,c);L(0==c);M(c&128)},,function(){b.i=b.i+1&255;L(0==b.i);M(b.i&128)},function(){var a=
E();N(a)},function(){},,function(){var a=D(x());K(b.i,a)},function(){var a=x();a=D(a);N(a)},function(){var a=x(),c=D(a);++c;c&=255;B(a,c);L(0==c);M(c&128)},,function(){var a=E();b.h&2&&J(a)},function(){var a=E();a=D(a)+(D(a+1)<<8);a=D(a+b.j);N(a)},,,,function(){var a=E()+b.i&255;a=D(a);b.h=b.h&254|a&1;N(a)},function(){var a=E()+b.i,c=D(a);++c;c&=255;B(a,c);L(0==c);M(c&128)},,function(){b.h|=8},function(){var a=x();a=D(a+b.j);N(a)},,,,function(){var a=x();a=D(a+b.i);N(a)},function(){var a=x()+b.i,
c=D(a);++c;c&=255;B(a,c);L(0==c);M(c&128)}];
function fa(){var a={A:function(c,d){c-=a.s;if(0>c||255<c)return"x";switch(c){case 255:d&128&&(a.c=0);a.c+=a.a*a.b;switch(d&-129){case 1:a.B=b.v+16;break;case 2:a.B=b.v+24;break;case 3:a.B=b.v+32;break;case 4:a.B=b.v+32}break;case 0:return a.a=d;case 1:return a.a+=d<<8;case 2:return a.a+=d<<16;case 3:return a.a+=d<<24;case 16:return a.b=d;case 17:return a.b+=d<<8;case 18:return a.b+=d<<16;case 19:return a.b+=d<<24;case 32:return a.c=d;case 33:return a.c+=d<<8;case 34:return a.c+=d<<16;case 35:return a.c+=
d<<24;case 36:return a.c+=d<<32;case 37:return a.c+=d<<40;case 38:return a.c+=d<<58;case 39:return a.c+=d<<56}return 0},S:function(c){var d=c-a.s;if(0>d||255<d)return"x";if(b.v<a.B)return F(a.s+255,0);switch(c&255){case 0:return F(c,a.a>>0);case 1:return F(c,a.a>>8);case 2:return F(c,a.a>>16);case 3:return F(c,a.a>>24);case 16:return F(c,a.b>>0);case 17:return F(c,a.b>>8);case 18:return F(c,a.b>>16);case 19:return F(c,a.b>>24);case 32:return F(c,a.c>>0);case 33:return F(c,a.c>>8);case 34:return F(c,
a.c>>16);case 35:return F(c,a.c>>24);case 36:return F(c,a.c>>32);case 37:return F(c,a.c>>40);case 38:return F(c,a.c>>48);case 39:return F(c,a.c>>56);case 255:return F(c,255)}return 0},s:33280,a:0,b:0,c:0,B:0};f.X=a}
function ea(){var a={A:function(l,n){l-=a.s;if(0>l||255<l)return"x";switch(l){case 0:return a.D=n;case 1:a.F=n;f.display.V(a.D,a.F,a.C);return;case 2:return a.C[0]=n;case 3:return a.C[1]=n;case 4:return a.C[2]=n;case 5:return a.P=n;case 6:a.F=n,0<a.P-a.D&&(a.context.fillStyle="rgb("+a.C.join(",")+")",a.context.fillRect(a.D*a.p,a.F*a.p,a.p*(a.P-a.D),a.p)),a.F++}return 0},V:function(l,n,r){a.context.fillStyle="rgb("+r.join(",")+")";a.context.fillRect(l*a.p,n*a.p,a.p,a.p)},s:33024,o:[256,192],p:2,C:[0,
0,0]},c=document.createElement("canvas");c.width=a.o[0]*a.p;c.height=a.o[1]*a.p;a.context=c.getContext("2d");var d=g("peri_display");d.style.width=c.width+"px";d.style.height=c.height+"px";d.appendChild(c);f.display=a}
function ca(){var a={A:function(c){c in a.G||(a.G[c]=0);a.G[c]++;return"x"},clear:function(){a.G=[];a.show()},show:function(){var c=[];for(d in a.G){var d=65535&d;var l=G(d),n=(G(d+1)<<8)+l;c.push("$"+u(d)+" → $"+t(l)+" %"+p(l)+" "+m(l)+" "+q(l)+" "+n.toString(10).padStart(5," "))}g("mem_wr_hgram").value=c.join("\n")}};a.clear();f.T=a}function da(){f.Z={A:function(a,c){if(4096!=a)return"x";g("out").value+=String.fromCharCode(c);Z();return 0}}}
function ha(){var a={A:function(l,n){l-=a.s;if(0>l||255<l)return"x";switch(l){case 0:a.exec(n);break;case 2:a.H[0]=n;break;case 3:a.H[1]=n;a.M();break;case 4:a.J[0]=n;break;case 5:a.J[1]=n,a.N()}return 0},exec:function(l){switch(l){case 0:a.clear();break;case 1:a.K=a.L();break;case 2:a.O(a.L());break;case 16:a.M=function(){};a.N=function(){};break;case 17:a.M=function(){a.O(a.L())};break;case 18:a.N=function(){a.O(a.L())}}},clear:function(){a.context.reset();a.context.fillStyle="rgb(0,40,20)";a.context.fillRect(0,
0,a.o[0],a.o[1]);a.context.strokeStyle="rgb(0,255,100)";a.context.lineWidth=1.5;a.context.translate(a.o[0]/2,a.o[1]/2)},W:function(){return[2*(a.H[1]<<8|a.H[0]<<0)/65536-1,-(2*(a.J[1]<<8|a.J[0]<<0)/65536-1)]},L:function(){var l=a.W(),n=a.o[1]/2;return[l[0]*n,l[1]*n]},O:function(l){var n=a.K;a.K=l;l=a.K;const r=a.context.createLinearGradient(n[0],n[1],l[0],l[1]);r.addColorStop(0,"green");r.addColorStop(1,"white");a.context.strokeStyle=r;a.context.beginPath();a.context.moveTo(n[0],n[1]);a.context.lineTo(l[0],
l[1]);a.context.stroke()},s:33792,o:[400,300],K:[0,0],H:[0,0],J:[0,0],M:function(){},N:function(){}},c=document.createElement("canvas");c.width=a.o[0];c.height=a.o[1];a.context=c.getContext("2d");var d=g("peri_tek");d.style.width=c.width+"px";d.style.height=c.height+"px";d.appendChild(c);a.Y=c.getContext("2d");a.clear();f.$=a}function U(a){var c=new FileReader;c.onload=function(){var d=c.result.replace(/^\s+/,"").replace(/\s+$/,"");g("asm").value=d};c.readAsText(a)}R=function(a){e.U=a};
function Z(){var a=g("out");a.scrollTop=a.scrollHeight}SO=function(a){g("out").value+=a.join("\n")+"\n";Z()};SS=function(a){g("asm").value=a};function ba(){function a(d){if(9==d.keyCode){d.preventDefault&&d.preventDefault();var l=d.selectionStart;d.value=d.value.substring(0,l)+"  "+d.value.substring(d.selectionEnd);d.selectionStart=d.selectionEnd=l+2;return!1}}var c=g("asm");c.addEventListener?c.addEventListener("keydown",a,!1):c.attachEvent&&c.attachEvent("onkeydown",a)};
